INSERT INTO airline VALUES("Delta Air Lines");
INSERT INTO airline VALUES("Alaska Airlines");
INSERT INTO airline VALUES("Southwest Airlines");
INSERT INTO airline VALUES("United Airlines");
INSERT INTO airline VALUES("American Airlines");
INSERT INTO airline VALUES("Air Canada");
INSERT INTO airline VALUES("Frontier Airlines");
INSERT INTO airline VALUES("KLM");
INSERT INTO airline VALUES("Aer Lingus");
INSERT INTO airline VALUES("Emirates");
INSERT INTO airline VALUES("Aeroflot");
INSERT INTO airline VALUES("Cathay Pacific");
INSERT INTO airline VALUES("Ryanair");
INSERT INTO airline VALUES("Air Italy");
INSERT INTO airline VALUES("Ravn Alaska");
INSERT INTO airline VALUES("Jet Blue");